version: '3'

services:
    front:
        image: front
        ports:
          -  5000:5000
    back:
        image: back
        ports:
          -  8000:8000
        environment:
          -  REDIS=redis_container
    redis_container:
        image: redis_container
        environment:
          -  REDIS=localhost