version: '3'

services:
    main:
        image: ml-main
        volumes:
          -  ./model:/src/model
          -  ./imgs:/src/imgs
    front:
        image: ml-front
        ports:
          -  3000:3000
    back:
        image: ml-back
        ports:
          -  5000:5000
        volumes:
          -  ./model:/usr/src/model
          -  ./imgs:/usr/src/imgs
