version: '3'

services:
    front:
        image: front
        ports:
          -  5000:5000
    back:
        image: back
        ports:
          -  8000:8000
        environment:
          -  REDIS=redis
          -  DB_HOST=db
          -  DB_USERNAME=user
          -  DB_PASSWORD=example
    redis_container:
        image: redis
        environment:
          -  REDIS=localhost
    db:
        image: postgres
        environment:
          -  POSTGRES_USER=user
          -  POSTGRES_PASSWORD=example
