version: '3'

services:
    front:
        image: front
        ports:
          -  5000:5000
    back:
        image: back
        ports:
          -  8000:8000
        environment:
          -  REDIS=redis_container
          -  DB_HOST=db_container
          -  DB_USERNAME=user
          -  DB_PASSWORD=example
    redis_container:
        image: redis_container
        environment:
          -  REDIS=localhost
    db:
        image: postgres
        container_name: db_container
        environment:
          -  POSTGRES_USER=user
          -  POSTGRES_PASSWORD=example